apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ignite-ingress
  namespace: ignite
spec:
  rules:
    http:
      paths:
      - path: /
        backend:
          serviceName: ignite-demo
          servicePort: web
